### ISSUE TITLE
The settings still show up as N/A after I inject.

### ISSUE THREAD

**Issue by Willtrilkillz** [fligger/FateInjector#10]
The settings still show up as N/A after I inject, so maybe I goofed but I followed the installation instructions to the letter am I missing something? maybe it's a problem on my end but I would love to here back from you. Everything here looks solid.

**Comment by aaryamanm128** [comment]
yes that might happen because the dll file is outdated . it is not a problem . maybe your version was 1.17 but the dll file was for 1.16 . so it did not work
