### ISSUE TITLE
I wanna get more information about your injector

### ISSUE THREAD

**Issue by WinkeyCheng** [fligger/FateInjector#13]
I tried to build a brand new injector with your injector as a base
But finally, I found that in your source code, there isn't any stuff like wxWidget 3.1.4 development pack, can you tell me the package you use to build this injector? Thanks

**Comment by fligger** [comment]
you need to download and include wxwidgets! 

https://wxwidgets.org/news/2020/07/wxwidgets-3.1.4-released/
