### ISSUE TITLE
VCRUNTIME140_1.dll was not found

### ISSUE THREAD

**Issue by igzhxnrii** [fligger/FateInjector#2]
![image](https://user-images.githubusercontent.com/73719170/97906425-7c6e4280-1cf8-11eb-8935-0ba4a3267066.png)

**Comment by fligger** [comment]
1. Go to https://support.microsoft.com/en-us/help/2977003
2. Scroll down and download the x64: vc_redist.x64.exe
3. Run the exe and install it
4. should now work
