### ISSUE TITLE
Cannot Inject a x86 DLL into a x86 Process on a 64 bit Machine

### ISSUE THREAD

**Issue by cxcubehd** [fligger/FateInjector#20]
It says injected but it doesn't succeed.

**Comment by fligger** [comment]
This is old code, But i think you would need to compile it in 32 bit to inject into 32 bit processes. 

The release binary is only designed for 64 bit processes. :)

**Comment by cxcubehd** [comment]
I am pretty sure that it possible to inject from a 64bit process. I will need to look more into it
