### ISSUE TITLE
Cant create config file

### ISSUE THREAD

**Issue by YeahAkis** [fligger/FateInjector#23]
whenever i try to inject or try to open the app it says this
![Screenshot_3](https://github.com/fligger/FateInjector/assets/87363509/6ca7f278-4c43-43ff-858e-996fc5a13494)

**Comment by fligger** [comment]
does your filepath include non latin characters?

**Comment by TeleportForward** [comment]
looking for player for apartment mission mastermind and doomsday hard difficulty，my socialclub user name is FROMathinkYoullD
with battleye on normally Play
