### ISSUE TITLE
cant use

### ISSUE THREAD

**Issue by Alana86521** [fligger/FateInjector#24]
every time i try to ue it my minecraft goes red screen then crashes

**Comment by LenRouxDev** [comment]
This isn't an issue with the client, its an anti-cheat measure Minecraft uses, essentially Minecraft detects any Injected Files (.DLLs etc) and Force Closes the game. This happens with other clients so its not just this one

**Comment by fligger** [comment]
Make sure the dll you inject ist compatible with your game version.

**Comment by KoryAlbright** [comment]
@fligger why don't you update this anymore?

**Comment by Alana86521** [comment]
oh btw i fixxed this i just needed visual studio

**Comment by TeleportForward** [comment]
looking for player for apartment mission mastermind and doomsday hard difficulty，my socialclub user name is FROMathinkYoullD
with battleye on normally Play
