### ISSUE TITLE
[Suggestion] New injection type

### ISSUE THREAD

**Issue by ItzLightyHD** [fligger/FateInjector#3]
You should add the texture pack injection in it, with a "Play" button

**Comment by fligger** [comment]
You mean I should add a button that opens the game?

**Comment by ItzLightyHD** [comment]
Yes, and that automatically adds the texture pack

**Comment by fligger** [comment]
I might add the open game button. Currently I want to keep the injector as transparent as possible. I want people to know how stuff works and what I am or I am not doing!

**Comment by ItzLightyHD** [comment]
I know, however, thanks ;)

Il giorno mer 9 dic 2020 alle ore 15:39 Fligger <notifications@github.com>
ha scritto:
