### ISSUE TITLE
Fate Injector

### ISSUE THREAD

**Issue by Crimpygamer65** [fligger/FateInjector#7]
My fate injector keeps crashing my Minecraft every time I inject it.

**Comment by poop201** [comment]
Same thing is happening to me and I think it is because a new version of Minecraft that came out and the injector does not support it so we will have to wait for a new version of the injector to come out.

**Comment by Shreyanshnarwe1** [comment]
Match your Minecraft version with version of the .dll .

**Comment by Shreyanshnarwe1** [comment]
or you can download the new injector for mcwin10 1.16.210 from herehttps://github.com/fligger/FateClient/releases/download/1.16.210-0/Fate.Client.dll

**Comment by fligger** [comment]
thanks
